export default LANG = 
    acceptSolutonsContest: "Прием решений с предварительной проверкой"
    TotalSubmits: "Всего попыток"
    Submits: "Попытки"
    Languages: "Языки программирования"

    Pts: "="
    Full: "Задач"
    Pl: "м"

    Points: "Баллы"
    SuccessfullTests: "Пройдено тестов"
    FirstWA: "Первый непройденный тест"
    Comment: "Комментарий"
    Attempt: 'Попытка'
    Token: "Запрос"
    UseToken: "Запросить результат"
    TokenRequestSent: "Запрос послан успешно"
    ReturnToMessages: "Вернуться к сообщениям"
    TokensRemaining: "Осталось запросов:"
    Wait: "Ждать"

    SuccessfullTests: "Пройдено тестов"
    NotAllTests: "Показаны результаты не всех тестов"
    ClickOnTestNumber: "Нажмите на номер теста или прокрутите страницу вниз чтобы посмотреть детали теста. Наведите мышь на результат теста, чтобы узнать, что это значит."
    ScrollToBottom: "Подробности тестирования под таблицей с тестами"
    TestingDetails: "Подробности тестирования"

    Program: "Программа:"
    CompileLog: "Протокол компиляции:"
    Input: "Входные данные:"
    ProgramOutput: "Вывод программы:"
    CorrectAnswer: "Правильный ответ (пример):"
    CheckerComment: "Комментарий тестирующей программы:"
    FileTooLongTruncated: "Файл слишком длинный, оставшаяся часть файла не показана"
    FileNonFoundProbablyNotCreated: "<Файл не найден. Возможно, он не был создан программой>"
